# Generated by Django 3.2.7 on 2021-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocdaApp', '0005_auto_20211003_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
