# Generated by Django 3.2.7 on 2021-10-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocdaApp', '0006_auto_20211003_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nota_Final',
        ),
        migrations.CreateModel(
            name='CursoMatriculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_Final', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocdaApp.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocdaApp.curso')),
            ],
        ),
    ]
