# Generated by Django 3.2.7 on 2021-10-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocdaApp', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocdaApp.area', unique=True),
        ),
        migrations.AlterField(
            model_name='cursomatriculado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocdaApp.curso', unique=True),
        ),
    ]
