# Generated by Django 3.2.7 on 2021-10-03 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocdaApp', '0011_alter_curso_docente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.AlterField(
            model_name='cursomatriculado',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
